# Generated by Django 4.2.9 on 2024-01-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
